server:
  port: 9008
spring:
  application:
    name: programHorizon-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/programHorizon-user?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: Mysql
    show-sql: true
    generate-ddl: true
  redis:
    cluster:
      ports:
        - 6379
        - 6380
        - 6381
        - 6382
        - 6383
        - 6384
      host: 127.0.0.1
      poolConfig:
        max-total: 6
        max-idle: 6
        max-wait-millis: -1
        min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

jwt:
  config:
    key: dillon
    ttl: 360000