server:
  port: 9006
spring:
  application:
    name: programHorizon-spit
  data:
    mongodb:
      uri: mongodb://localhost:27017/spitdb
  redis:
    cluster:
      ports:
        - 6379
        - 6380
        - 6381
        - 6382
        - 6383
        - 6384
      host: 127.0.0.1
      poolConfig:
        max-total: 6
        max-idle: 6
        max-wait-millis: -1
        min-idle: 0