server:
  port: 12000
spring:
  application:
    name: programHorizon-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiekunlong/programHorizon-config.git
          username: Dillon
          password: mayun123456
          default-label: master
  rabbitmq:
    host: 47.115.94.160
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh