server:
  port: 9007
spring:
  application:
    name: programHorizon-search

  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9301
      cluster-name: my-elasticsearch

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true