server:
  port: 9001
spring:
  application:
    name: programHorizon-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/programHorizon-base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: Mysql
    show-sql: true
    generate-ddl: true