server:
  port: 6868
spring:
  application:
    name: programhorizon_eureka
eureka:
  client:
    fetch-registry: false  #是否从Eureka中获取注册信息
    register-with-eureka: false  #是否将自己注册到Eureka服务中，本身就是所有无需注册
    service-url:
      defaultZone: http://192.168.107.128:6868/eureka
  server:
    enable-self-preservation: false  #关闭自我保护
    eviction-interval-timer-in-ms: 5000 #每隔5秒进行一次服务列表清理